spring:
    datasource:
        url: jdbc:sqlite::resource:db/accountBook-db.sqlite
        username:
        password:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true


